import tkinter as tk
from tkinter import *

root = tk.Tk()
root.title('Calculator')
root.geometry("400x400")
# label = tk.Label(root,text="0",font=("Arial",24),bg="black",fg='white', width=71, anchor="e")
label = tk.Label(root, text="Akash Kumar Singh", font=("Algerian",26), bg="black", fg='white', anchor="e")
label.grid(column=0, row=0, columnspan=4,sticky='NSEW')
for i in range(4):
    root.columnconfigure(i,weight=1)
for i in range(6):
    root.rowconfigure(i,weight=1)

btn_1 = tk.Button(root,text="1",font=("Algerian",24),bg="black",fg="white")
btn_1.grid(column=0,row=1,columnspan=1,rowspan=1,sticky="NSEW")
btn_2 = tk.Button(root,text="2",font=("Algerian",24),bg="black",fg="white")
btn_2.grid(column=1,row=1,columnspan=1,rowspan=1,sticky="NSEW")
btn_3 = tk.Button(root,text="3",font=("Algerian",24),bg="black",fg="white")
btn_3.grid(column=2,row=1,columnspan=1,rowspan=1,sticky="NSEW")
btn_d = tk.Button(root,text="/",font=("Algerian",24),bg="black",fg="white")
btn_d.grid(column=3,row=1,columnspan=1,rowspan=1,sticky="NSEW")
btn_4 = tk.Button(root,text="4",font=("Algerian",24),bg='Black',fg='white')
btn_4.grid(column=0,row=2,rowspan=1,columnspan=1,sticky="NSEW")
btn_5 = Button(root,text="5",font=("Algerian",24),bg="Black",fg='white')
btn_5.grid(column=1,row=2,rowspan=1,columnspan=1,sticky="NSEW")
btn_6 = Button(root,text="6",font=("Algerian",24),bg="Black",fg='white')
btn_6.grid(column=2,row=2,rowspan=1,columnspan=1,sticky="NSEW")
btn_mul = Button(root,text="*",font=("Algerian",24),bg="Black",fg='white')
btn_mul.grid(column=3,row=2,rowspan=1,columnspan=1,sticky="NSEW")
btn_7 = Button(root,text="7",font=("Algerian",24),bg="Black",fg='white')
btn_7.grid(column=0,row=3,rowspan=1,columnspan=1,sticky="NSEW")
btn_8 = Button(root,text="8",font=("Algerian",24),bg="Black",fg='white')
btn_8.grid(column=1,row=3,rowspan=1,columnspan=1,sticky="NSEW")
btn_9 = Button(root,text="9",font=("Algerian",24),bg="Black",fg='white')
btn_9.grid(column=2,row=3,rowspan=1,columnspan=1,sticky="NSEW")
btn_sub = Button(root,text="-",font=("Algerian",24),bg="Black",fg='white')
btn_sub.grid(column=3,row=3,rowspan=1,columnspan=1,sticky="NSEW")
btn_eq = Button(root,text="=",font=("Algerian",24),bg="Black",fg='white')
btn_eq.grid(column=2,row=4,rowspan=1,columnspan=1,sticky="NSEW")
btn_dec = Button(root,text=".",font=("Algerian",24),bg="Black",fg='white')
btn_dec.grid(column=0,row=4,rowspan=1,columnspan=1,sticky="NSEW")
btn_add = Button(root,text="+",font=("Algerian",24),bg="Black",fg='white')
btn_add.grid(column=3,row=4,rowspan=1,columnspan=1,sticky="NSEW")
btn_0 = Button(root,text="0",font=("Algerian",24),bg="Black",fg='white')
btn_0.grid(column=1,row=4,rowspan=1,columnspan=1,sticky="NSEW")
btn_mod = Button(root,text="%",font=("Algerian",24),bg="Black",fg='white')
btn_mod.grid(column=1,row=5,rowspan=1,columnspan=1,sticky="NSEW")
root.mainloop()